/* confdefs.h */
#define PACKAGE_NAME "alien"
#define PACKAGE_TARNAME "alien"
#define PACKAGE_VERSION "0.7.0"
#define PACKAGE_STRING "alien 0.7.0"
#define PACKAGE_BUGREPORT "http://mascarenhas.github.com/alien"
#define PACKAGE_URL ""
#define PACKAGE "alien"
#define VERSION "0.7.0"
#define STDC_HEADERS 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRING_H 1
#define HAVE_MEMORY_H 1
#define HAVE_STDINT_H 1
#define LT_OBJDIR ".libs/"
#define STDC_HEADERS 1
#define HAVE_FFI_H 1